name: example
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_trimmer:
    path: ../

  video_player: ^2.2.19
  file_picker: ^4.5.0

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
